export const ROUTES = {
  SPLASH: 'SplashScreen',
  GET_STARTED: 'GetStartedScreen',
  LOGIN: 'LoginScreen',
  HOME: 'HomeScreen',
  INTRO: 'IntroRoot',
  ONBOARDING: 'OnboardingScreen',
  STARTLEARNING: 'SartLearningScreen',
  SIGNUP: 'signupScreen',
  SIGNIN: 'signinScreen',
  AUTH: 'AuthRoot',
  Main: 'MainRoot',
  SEARCH: 'SearchScreen',
  DETAILS: 'DetailsSCreen',
  PROFILE: 'ProfileScreen',
  CURRENT_COURSES: 'CurrenctCouseScreen',
  SUBJECT_DETAILS: 'SubjectDetailsScreen',
};
